### ISSUE TITLE
Purchase NFT with 4000 GREPCC error

### ISSUE THREAD

**Issue by Topandhi** [TaylorHawkes/grepper_contributor_coin_contract#3]
I cannot purchase NFT with my GREPCC.

**Comment by Topandhi** [comment]
![error log grepper](https://user-images.githubusercontent.com/85047888/231321412-41616411-3eb9-4b2f-9ac3-33a31845a6b0.PNG)
screenshoot

**Comment by Topandhi** [comment]
i have copy last response when i click Redeem with GREPCC, it says "Transaction simulation failed: Attempt to debit an account but found no record of a prior credit."
![error 2](https://user-images.githubusercontent.com/85047888/237023181-b7062d9a-3333-4b7b-b717-49fdb9d005d4.PNG)

**Comment by Topandhi** [comment]
i looked at the source code and i assume its error in here

![grepcc bug xx](https://github.com/CodeGrepper/grepper_contributor_coin_contract/assets/85047888/23fe0978-53f1-4e16-90aa-3a5bc9fb8298)

**Comment by makstyle119** [comment]
Does anyone get any **solution** because I'm facing the same error

**Comment by Topandhi** [comment]
Not yet
